

byte val; 
const int LED2 = 2; 
const int LED3 = 3; 
const int LED4 = 4;
const int LED5 = 5; 
const int LED6 = 6; 
const int LED7 = 7;
void setup() {
 
  pinMode(LED2, OUTPUT); 
  pinMode(LED3, OUTPUT); 
  pinMode(LED4, OUTPUT);
  pinMode(LED5, OUTPUT);
  pinMode(LED6, OUTPUT);
  pinMode(LED7, OUTPUT);
  Serial.begin(9600); 
}

void loop() {
  if (Serial.available()) { 
    val = Serial.read(); 
  }
  if (val == 0) { 

    digitalWrite(LED2, LOW);
    
  }
  else if (val == 1) { 

 digitalWrite(LED2, HIGH); 
 delay(500); 
 digitalWrite(LED3, HIGH);
 delay(1200); 
 digitalWrite(LED4, HIGH);
 delay(1100); 
 digitalWrite(LED5, HIGH); 
 delay(1000); 
 digitalWrite(LED6, HIGH); 
 delay(1500); 
 digitalWrite(LED2, LOW); 
 digitalWrite(LED3, LOW);
 digitalWrite(LED4, LOW);
 delay(500); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED7, HIGH);
 digitalWrite(LED2, HIGH);  
 delay(2000); 
 digitalWrite(LED7, HIGH); 
 delay(500); 
 digitalWrite(LED6, HIGH);
 delay(500); 
 digitalWrite(LED5, HIGH);
 delay(500); 
 digitalWrite(LED4, HIGH); 
 delay(500);
 digitalWrite(LED2, LOW); 
 delay(1500);
 digitalWrite(LED2, HIGH); 
 delay(1000);
  digitalWrite(LED7, LOW); 
  digitalWrite(LED6, LOW); 
  digitalWrite(LED5, LOW); 
  digitalWrite(LED4, LOW); 
  digitalWrite(LED3, LOW); 
  digitalWrite(LED2, LOW); 
  delay(2000);
  digitalWrite(LED7, HIGH); 
  delay(2000);
 digitalWrite(LED2, HIGH); 
 delay(500); 
 digitalWrite(LED3, HIGH);
 delay(1100); 
 digitalWrite(LED4, HIGH);
 delay(900); 
 digitalWrite(LED5, HIGH); 
 delay(1000); 
 digitalWrite(LED6, HIGH); 
 delay(1500); 
 digitalWrite(LED2, LOW); 
 digitalWrite(LED3, HIGH);
 digitalWrite(LED4, LOW);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED6, HIGH); 
 delay(500);
 digitalWrite(LED2, HIGH); 
 digitalWrite(LED3, LOW);
 digitalWrite(LED4, HIGH);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED6, LOW); 
 delay(2500);
 digitalWrite(LED5, HIGH); 
 delay(500);
 digitalWrite(LED5, LOW); 
 delay(500); 
 digitalWrite(LED5, HIGH); 
 delay(500); 
 digitalWrite(LED5, LOW); 
 delay(1500);
 digitalWrite(LED6, HIGH); 
 delay(1000);
 digitalWrite(LED3, HIGH); 
 delay(1000);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
 delay(3000);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
 delay(500); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
 delay(400);
 digitalWrite(LED3, HIGH);
 delay(200);
 digitalWrite(LED4, HIGH);
 delay(800);
 digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH);
 delay(50);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW);
 delay(50);  
 digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH);
 delay(50);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW); 
 delay(50);
 digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH); 
 delay(50);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW); 
 delay(500);
digitalWrite(LED5, LOW); 
delay(100);
digitalWrite(LED5, HIGH);   
delay(100);
digitalWrite(LED5, LOW);    
delay(100);  
digitalWrite(LED5, HIGH);     
delay(100);
digitalWrite(LED2, LOW);
delay(100);
digitalWrite(LED2, HIGH);
delay(100);
digitalWrite(LED2, LOW);
delay(600);  
digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH);
 delay(100);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW);
 delay(100);  
 digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH);
 delay(100);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW); 
 delay(100);
 digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH); 
 delay(50);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW);   
  delay(50);
 digitalWrite(LED7,HIGH);
 digitalWrite(LED6, HIGH);   
 delay(50);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
 delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
  delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
  delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
   delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
   delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);  
    delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
  delay(400);
 digitalWrite(LED2, HIGH);
  delay(100);
  digitalWrite(LED2, LOW);
  digitalWrite(LED7, HIGH); 
  delay(25);
  digitalWrite(LED6, HIGH); 
    delay(25);
  digitalWrite(LED5, HIGH); 
  delay(25);
  digitalWrite(LED4, HIGH); 
  delay(25);
  digitalWrite(LED3, HIGH); 
  delay(25);
  digitalWrite(LED2, HIGH); 
     delay(200); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
   delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
     delay(200); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
  delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
delay(100);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW);  
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
  delay(100);
digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 delay(100);
digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 delay(100);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 delay(100);
digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(1000); 
  digitalWrite(LED7, HIGH); 
  digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
delay(1000);  
   digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
  delay(1000); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 delay(1000);  
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
  delay(1000);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
  delay(1000); 
    digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW);  
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
  delay(1000);  
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, HIGH);
  delay(1000);
 digitalWrite(LED6, HIGH);  
 digitalWrite(LED2, LOW);
  delay(1000);
  digitalWrite(LED2, HIGH); 
 delay(500); 
 digitalWrite(LED3, HIGH);
  delay(200);
  digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH);
 delay(50);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW);
 delay(50);  
 digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH);
 delay(50);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW); 
 delay(50);
 digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH); 
 delay(50);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW);   
  delay(50);
 digitalWrite(LED7,HIGH);
 digitalWrite(LED6, HIGH);   
 delay(50);
  digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW); 
 delay(50);
 digitalWrite(LED7, HIGH);
 digitalWrite(LED6, HIGH); 
 delay(50);
 digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW);   
  delay(50);
 digitalWrite(LED7,HIGH);
 digitalWrite(LED6, HIGH);   
 delay(50);
  digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW);   
  delay(50);
   digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
  delay(200);
 digitalWrite(LED2, HIGH);
  delay(20); 
 digitalWrite(LED2, LOW);
  delay(200);
  digitalWrite(LED2, HIGH);
  delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
  delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
    delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
  delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
   delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
  delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
   delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
  delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
   delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
  delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
   delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
  delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
   delay(50);
    digitalWrite(LED2, LOW);
  delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
   delay(100);
  digitalWrite(LED2, LOW);
  delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);
  digitalWrite(LED2, LOW);
  delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);   
  digitalWrite(LED2, LOW);
  delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);
  digitalWrite(LED2, LOW);
  delay(100);
  digitalWrite(LED2, HIGH);
   delay(100);
   digitalWrite(LED2, LOW);
  delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);
  digitalWrite(LED2, LOW);
  delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);
   digitalWrite(LED2, LOW);
  delay(100);
  digitalWrite(LED2, HIGH);
  delay(100);
  digitalWrite(LED2, LOW);
  delay(100);
     digitalWrite(LED2, HIGH);
     delay(100);
     digitalWrite(LED2, LOW);
  delay(100); 
  digitalWrite(LED2, HIGH);
  delay(50);
   digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
  delay(50);
  digitalWrite(LED2, LOW);
  delay(50);
  digitalWrite(LED2, HIGH);
   delay(50);
   digitalWrite(LED2, LOW);
  delay(50);
    digitalWrite(LED7, LOW);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW);       
   delay(1000); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH);  
   delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);       
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
   delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);    
      delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
   delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);     
     delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
     delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
       delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
        delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
       delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);   
   delay(100); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED2, HIGH);  
delay(500);
   digitalWrite(LED5, HIGH);
  delay(500);
   digitalWrite(LED6, HIGH);
     delay(500); 
   digitalWrite(LED4, HIGH); 
 delay(500); 
    digitalWrite(LED3, HIGH); 
 delay(400);
     digitalWrite(LED7, HIGH); 
 delay(1400);
digitalWrite(LED7, LOW); 
(1400);
    digitalWrite(LED3, LOW); 
 delay(1000);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW);  
 digitalWrite(LED2,LOW); 
  }
  else if (val == 2) { // If 2 received

    
  }
  else if (val == 3) { // If 3 received
     digitalWrite(LED3, HIGH);
 delay(1200);   
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW);
 delay(1800); 
 digitalWrite(LED2, HIGH);
  delay(1000);
  digitalWrite(LED2, LOW);
  digitalWrite(LED3, HIGH);
  digitalWrite(LED4, LOW);
   delay(1700);
    digitalWrite(LED2, HIGH);
 delay(1000);   
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW);
 delay(1000); 
  digitalWrite(LED2, HIGH);
  delay(600);
  digitalWrite(LED2, LOW);
  digitalWrite(LED3, HIGH);
  digitalWrite(LED4, LOW);
   delay(1000);
  digitalWrite(LED3, LOW);
  digitalWrite(LED4, HIGH);
  delay(1500);
 digitalWrite(LED7, HIGH);  
 digitalWrite(LED4, LOW); 
   delay(200); 
 digitalWrite(LED6, HIGH); 
    delay(200); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED3, LOW); 
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH);  
      delay(200);
 digitalWrite(LED3, HIGH); 
      delay(200);
 digitalWrite(LED2, HIGH);
        delay(200);
 digitalWrite(LED2, LOW);
          delay(200);
 digitalWrite(LED3, LOW); 
            delay(200);
 digitalWrite(LED4, LOW); 
            delay(200);
 digitalWrite(LED5, LOW); 
            delay(200);
 digitalWrite(LED6, LOW); 
            delay(200);
 digitalWrite(LED7, LOW); 
delay(200);
 digitalWrite(LED7, HIGH); 
   delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
    delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
        delay(200);
 digitalWrite(LED2, LOW);
          delay(200);
 digitalWrite(LED3, LOW); 
            delay(200);
 digitalWrite(LED4, LOW); 
            delay(200);
 digitalWrite(LED5, LOW); 
            delay(200);
 digitalWrite(LED6, LOW); 
            delay(200);
 digitalWrite(LED7, LOW); 
delay(300);
digitalWrite(LED7, HIGH);  
 digitalWrite(LED3, HIGH); 
   delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH);   
 digitalWrite(LED3, HIGH); 
    delay(200);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
      delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
        delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED2, LOW);
          delay(200);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, LOW); 
            delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
            delay(200);
 digitalWrite(LED5, LOW);  
 digitalWrite(LED2, LOW);
            delay(200); 
 digitalWrite(LED6, LOW);   
            delay(200);
 digitalWrite(LED7, LOW);  
delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);   
   delay(200);
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
    delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW);  
      delay(200);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
      delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
        delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
          delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW);  
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, HIGH);
            delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH);  
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED2, LOW);
            delay(200);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
            delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
            delay(200);
 digitalWrite(LED7, LOW);   
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
 delay(200);
 digitalWrite(LED6, HIGH); 
   delay(200);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
    delay(200); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
      delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
      delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
        delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
          delay(5);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
           delay(500);
    digitalWrite(LED6, LOW);
      delay(500);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
 delay(150);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
           delay(500);

 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 delay(500);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(500);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(800);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
 delay(500);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
           delay(500);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
 delay(500);
  digitalWrite(LED6, HIGH);
delay(900);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
 delay(500);
 digitalWrite(LED6, LOW);  
 digitalWrite(LED4, HIGH); 
           delay(500);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
 delay(500);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(500);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(5);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
 delay(500);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
           delay(500);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
 delay(500);
  digitalWrite(LED6, HIGH);
 delay(500);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 delay(500);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
           delay(500); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
 delay(700);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(500);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(5);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
 delay(500);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH);  
           delay(500);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
 delay(500);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
  delay(1300);
   digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
    delay(1400);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
     delay(1400);
   digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
  delay(500);
digitalWrite(LED7, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
   delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
    delay(200); 
 digitalWrite(LED5, HIGH); 
      delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
      delay(200);
 digitalWrite(LED3, HIGH); 
      delay(200);
 digitalWrite(LED2, HIGH);
        delay(200);
 digitalWrite(LED2, LOW);
          delay(200);
 digitalWrite(LED3, LOW); 
            delay(200);
 digitalWrite(LED4, LOW); 
            delay(200);
 digitalWrite(LED5, LOW); 
            delay(200);
 digitalWrite(LED6, LOW); 
            delay(200);
 digitalWrite(LED7, LOW); 
delay(200);
 digitalWrite(LED7, HIGH); 
   delay(200);
 digitalWrite(LED6, HIGH); 
    delay(200);
 digitalWrite(LED5, HIGH); 
      delay(200);
 digitalWrite(LED4, HIGH); 
      delay(200);
 digitalWrite(LED3, HIGH); 
      delay(200); 
 digitalWrite(LED2, HIGH);
        delay(200);
 digitalWrite(LED2, LOW);
          delay(200);
 digitalWrite(LED3, LOW); 
            delay(200); 
 digitalWrite(LED4, LOW); 
            delay(200); 
 digitalWrite(LED5, LOW); 
            delay(200);
 digitalWrite(LED6, LOW); 
            delay(200);
 digitalWrite(LED7, LOW); 
delay(300);
digitalWrite(LED7, HIGH); 
 digitalWrite(LED3, HIGH); 
   delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
    delay(200);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
      delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
        delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED2, LOW);
          delay(200);
 digitalWrite(LED6, LOW);  
 digitalWrite(LED3, LOW); 
            delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
            delay(200);
 digitalWrite(LED5, LOW);  
            delay(200);
 digitalWrite(LED6, LOW); 
            delay(200);
 digitalWrite(LED7, LOW);  
delay(400);  
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
    delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW);  
      delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
      delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
        delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
          delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW);  
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, HIGH);
            delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED2, LOW);
            delay(200);
 digitalWrite(LED4, LOW);  
 digitalWrite(LED2, HIGH);
            delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW);   
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, LOW);
            delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED3, LOW); 
 delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
   delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW);  
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
    delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
      delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
      delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
      delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
        delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
          delay(5);
 digitalWrite(LED7, HIGH);  
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH);  
 digitalWrite(LED2, HIGH);
           delay(500);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
           delay(100);  
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(100);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(100); 
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(100);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(100); 
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
           delay(50);  
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(50); 
       digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
           delay(50);  
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(50);  
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(50); 
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(50);          
   delay(5);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
 delay(500);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
           delay(500);

 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
digitalWrite(LED7, LOW); 
delay(100);
 digitalWrite(LED7, HIGH); 
delay(100);
digitalWrite(LED7, LOW); 
delay(100);
digitalWrite(LED7, HIGH); 
delay(100);
digitalWrite(LED7, LOW); 
delay(100);
 digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(500);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(50);
digitalWrite(LED7, HIGH); 
delay(50);
digitalWrite(LED7, LOW); 
delay(5);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
 delay(500);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
           delay(500);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 delay(100);  
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(100);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(100); 
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(100);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(100); 
       delay(100);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(100); 
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(100);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(100);              
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
           delay(50);  
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(50); 
       digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
           delay(50);  
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(50);  
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(50); 
    digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
  delay(50);  
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
    delay(50);          
    delay(5);
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
 delay(500);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
           delay(500);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
  
  }
  else if (val == 4) { // If 4 received
    delay(2800);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
  delay(1150);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(200);
  digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(150);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(150);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(500); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
delay(300);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED2, LOW);
  delay(550);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
  delay(1150); 
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(150);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(500);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
delay(300);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED2, LOW);
  delay(550);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 delay(1200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH);  
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(150);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(500);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
delay(300);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED2, LOW);
  delay(550);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
delay(1200);
digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(150);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(500); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
delay(300);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH);  
 digitalWrite(LED2, LOW);
  delay(550);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
delay(50);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
delay(200);
  digitalWrite(LED7, HIGH);  
 digitalWrite(LED2, LOW); 
delay(200);
   digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
delay(200); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
delay(200);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(200); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(200);
  digitalWrite(LED7, HIGH); 
delay(200);
   digitalWrite(LED7, LOW);  
 digitalWrite(LED4, HIGH); 
delay(200);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
delay(200);
   digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED2, LOW);
delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
delay(200);
   digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH);  
delay(200);
   digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
delay(200); 
 digitalWrite(LED6, LOW);   
 digitalWrite(LED2, HIGH);
delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
delay(200);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
delay(200);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(200);
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(200);   
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(200);
 digitalWrite(LED7, HIGH); 
delay(200);
   digitalWrite(LED7, LOW);  
 digitalWrite(LED4, HIGH);  
delay(200);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
delay(200);
   digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, LOW);
delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED3, LOW); 
delay(200);
 digitalWrite(LED6, HIGH);  
 digitalWrite(LED3, LOW); 
delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH);  
delay(200);
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(200);
 digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
delay(200);
   digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
delay(200);
 digitalWrite(LED6, HIGH); 
delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
delay(200);
   digitalWrite(LED7, HIGH);  
 digitalWrite(LED5, LOW);  
delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(200); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
  delay(200);
 digitalWrite(LED7, HIGH); 
delay(200);
   digitalWrite(LED7, LOW);  
 digitalWrite(LED4, HIGH); 
delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
delay(100);
    digitalWrite(LED7, HIGH);   
delay(200);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(200);
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
  delay(200);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
    delay(200);
    digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
  delay(100);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);  
      delay(200);
    digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH); 
delay(300);
digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
delay(200);
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW); 
delay(250);
  digitalWrite(LED7, HIGH); 
  delay(300);
 digitalWrite(LED5, HIGH); 
 delay(300);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
  delay(300);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
   digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
  delay(200);
 digitalWrite(LED6, LOW); 
  digitalWrite(LED7, LOW); 
   delay(1000); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW);  
 delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, LOW);
  delay(200);  
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED3, LOW); 
   delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW);  
 digitalWrite(LED2, HIGH);
     delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED2, LOW);
     delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
    delay(200);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, HIGH);
      delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED3, HIGH); 
     delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, LOW);
     delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH);  
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, HIGH);
  delay(200);
   digitalWrite(LED7, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, LOW);
 delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
  delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
   delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
     delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
     delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED5, LOW);  
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, HIGH);
    delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED2, LOW);
      delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
     delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH);  
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, HIGH);
     delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
  delay(200);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
  delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
   delay(200);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
     delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH);  
 digitalWrite(LED2, HIGH);
     delay(200);
 digitalWrite(LED6, LOW); 
    delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
      delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED3, HIGH); 
     delay(200);
 digitalWrite(LED2, LOW);
     delay(200);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED2, HIGH);
  delay(200);
 digitalWrite(LED7, HIGH);  
 digitalWrite(LED3, LOW); 
 delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH);  
 digitalWrite(LED2, LOW);
  delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW);  
   delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
     delay(200);
 digitalWrite(LED6, HIGH);  
 digitalWrite(LED3, LOW); 
     delay(200); 
 digitalWrite(LED6, LOW);  
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
    delay(200);
  digitalWrite(LED7, HIGH);  
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
      delay(200);
  digitalWrite(LED7, LOW);  
 digitalWrite(LED3, HIGH); 
     delay(200);
 digitalWrite(LED2, LOW);
     delay(200);  
 digitalWrite(LED5, LOW);  
 digitalWrite(LED2, HIGH);
  delay(200);
   digitalWrite(LED7, HIGH);  
 digitalWrite(LED2, LOW);
 delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
  delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
   delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, HIGH);
     delay(200);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED3, LOW);
 digitalWrite(LED2, LOW);
     delay(200); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
    delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
      delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED3, HIGH); 
     delay(200);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
     delay(200);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, HIGH);
     delay(200);
        
 digitalWrite(LED5,HIGH); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
 digitalWrite(LED2, LOW);
     delay(200);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED4, HIGH);  
 digitalWrite(LED2, HIGH);
delay(100);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW); 
 digitalWrite(LED2, LOW);
delay(5);
 digitalWrite(LED7, HIGH); 
 delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
 delay(150);
  digitalWrite(LED4, LOW); 
  digitalWrite(LED2, HIGH);
  delay(150); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED2, LOW);
     delay(150);
  digitalWrite(LED5, LOW); 
 digitalWrite(LED6, HIGH); 
     delay(150);
  digitalWrite(LED7, HIGH); 
digitalWrite(LED6, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
  digitalWrite(LED3, HIGH); 
 delay(150);
  digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
  delay(150);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
     delay(150);
digitalWrite(LED5, HIGH); 
digitalWrite(LED2, LOW);
  delay(150);
   digitalWrite(LED7, HIGH); 
   digitalWrite(LED5, LOW); 
  delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 delay(150);
digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
   delay(150);
 digitalWrite(LED6, HIGH); 
digitalWrite(LED3, LOW); 
     delay(150);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED6, LOW); 
     delay(150);
  digitalWrite(LED7, HIGH);  
 digitalWrite(LED5, LOW); 
    delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED2, HIGH);
      delay(150);
  digitalWrite(LED7, HIGH); 
digitalWrite(LED2, LOW);
     delay(150);
  digitalWrite(LED7, LOW); 
digitalWrite(LED4, HIGH); 
delay(150);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
  delay(150);
 digitalWrite(LED6, HIGH); 
digitalWrite(LED2, LOW);
 delay(150);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
  delay(150);
 digitalWrite(LED5, LOW); 
  digitalWrite(LED3, HIGH); 
delay(150);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED3, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
     delay(150);
  digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
  delay(150);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED3, LOW); 
   digitalWrite(LED7, LOW); 
 digitalWrite(LED3, LOW);
    delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
    delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH);
     delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
    delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH);
    delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
    delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH);
   delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH);
   delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
 delay(100);
 digitalWrite(LED3, HIGH);
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED7, HIGH); 
      delay(150);
 digitalWrite(LED2, LOW); 
 digitalWrite(LED3, LOW);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED5, LOW); 
 digitalWrite(LED6, LOW); 
 digitalWrite(LED7, LOW); 
     delay(150);
 digitalWrite(LED4, HIGH); 
  delay(150);
digitalWrite(LED7, HIGH); 
 digitalWrite(LED4, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
digitalWrite(LED5, HIGH); 
  delay(150);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED3, HIGH); 
 delay(150);
 digitalWrite(LED7, HIGH); 
digitalWrite(LED3, LOW);
 delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
 delay(150);
  digitalWrite(LED4, LOW); 
  digitalWrite(LED2, HIGH);
  delay(150); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED2, LOW);
     delay(150);
  digitalWrite(LED5, LOW); 
 digitalWrite(LED6, HIGH); 
     delay(150);
  digitalWrite(LED7, HIGH); 
digitalWrite(LED6, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
  digitalWrite(LED3, HIGH); 
 delay(150);
      digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
  delay(150);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
     delay(150);
digitalWrite(LED5, HIGH); 
digitalWrite(LED2, LOW);
  delay(150);
   digitalWrite(LED7, HIGH); 
   digitalWrite(LED5, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
delay(150);
digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
delay(150);
 digitalWrite(LED6, HIGH); 
digitalWrite(LED3, LOW); 
delay(150);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED6, LOW); 
     delay(150);
  digitalWrite(LED7, HIGH);  
 digitalWrite(LED5, LOW); 
   delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED2, HIGH);
      delay(150);
  digitalWrite(LED7, HIGH); 
digitalWrite(LED2, LOW);
     delay(150);
  digitalWrite(LED7, LOW); 
digitalWrite(LED4, HIGH); 
delay(150);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
  delay(150);
 digitalWrite(LED6, HIGH); 
digitalWrite(LED2, LOW);
 delay(150);
 digitalWrite(LED6, LOW); 
 digitalWrite(LED5, HIGH); 
  delay(150);
 digitalWrite(LED5, LOW); 
  digitalWrite(LED3, HIGH); 
   delay(150);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED3, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
     delay(150);
  digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
    delay(150);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED3, LOW); 
      delay(150);
digitalWrite(LED5, LOW); 
digitalWrite(LED2, HIGH);
     delay(150);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED2, LOW);
     delay(150); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED6, LOW);
  delay(150);
digitalWrite(LED7, HIGH); 
 digitalWrite(LED4, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
digitalWrite(LED5, HIGH); 
  delay(150);
digitalWrite(LED7, HIGH); 
digitalWrite(LED6, HIGH);
digitalWrite(LED5, HIGH); 
digitalWrite(LED4, HIGH);
digitalWrite(LED3, HIGH); 
digitalWrite(LED2, HIGH);
 delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
 delay(150);
  digitalWrite(LED4, LOW); 
  digitalWrite(LED2, HIGH);
  delay(150); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED2, LOW);
     delay(150);
  digitalWrite(LED5, LOW); 
 digitalWrite(LED6, HIGH); 
     delay(150);
  digitalWrite(LED7, HIGH); 
digitalWrite(LED6, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
  digitalWrite(LED3, HIGH); 
 delay(150);
  digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
  delay(150);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
     delay(150);
digitalWrite(LED5, HIGH); 
digitalWrite(LED2, LOW);
  delay(150);
   digitalWrite(LED7, HIGH); 
   digitalWrite(LED5, LOW); 
  delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 delay(150);
digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
   delay(150);
digitalWrite(LED6, HIGH); 
 digitalWrite(LED3, LOW); 
   delay(150);
  digitalWrite(LED7, HIGH); 
 digitalWrite(LED6, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
     delay(150);
  digitalWrite(LED4, LOW); 
 digitalWrite(LED3, HIGH); 
    delay(150);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED3, LOW); 
      delay(150);
digitalWrite(LED5, LOW); 
digitalWrite(LED2, HIGH);
     delay(150);
 digitalWrite(LED6, HIGH); 
 digitalWrite(LED2, LOW);
     delay(150); 
 digitalWrite(LED4, HIGH); 
 digitalWrite(LED6, LOW);
  delay(150);
digitalWrite(LED7, HIGH); 
 digitalWrite(LED4, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
digitalWrite(LED5, HIGH); 
  delay(150);
 digitalWrite(LED5, LOW); 
 digitalWrite(LED3, HIGH); 
 delay(150);
 digitalWrite(LED7, HIGH); 
digitalWrite(LED3, LOW);
 delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
 delay(150);
  digitalWrite(LED4, LOW); 
  digitalWrite(LED2, HIGH);
  delay(150); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED2, LOW);
     delay(150);
  digitalWrite(LED5, LOW); 
 digitalWrite(LED6, HIGH); 
     delay(150);
  digitalWrite(LED7, HIGH); 
digitalWrite(LED6, LOW); 
delay(550);
  digitalWrite(LED7, LOW); 
  digitalWrite(LED3, HIGH); 
 delay(550);
      digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
  delay(550);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
     delay(150);
digitalWrite(LED5, HIGH); 
digitalWrite(LED2, LOW);
  delay(150);
   digitalWrite(LED7, HIGH); 
   digitalWrite(LED5, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
delay(150);
digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
delay(150);
 digitalWrite(LED6, HIGH); 
digitalWrite(LED3, LOW); 
delay(150);
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED6, LOW); 
     delay(150);
  digitalWrite(LED7, HIGH);  
 digitalWrite(LED5, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED4, HIGH); 
 delay(150);
  digitalWrite(LED4, LOW); 
  digitalWrite(LED2, HIGH);
  delay(150); 
 digitalWrite(LED5, HIGH); 
 digitalWrite(LED2, LOW);
     delay(150);
  digitalWrite(LED5, LOW); 
 digitalWrite(LED6, HIGH); 
     delay(150);
  digitalWrite(LED7, HIGH); 
digitalWrite(LED6, LOW); 
delay(150);
  digitalWrite(LED7, LOW); 
  digitalWrite(LED3, HIGH); 
 delay(150);
  digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, LOW); 
  delay(150);
 digitalWrite(LED4, LOW); 
 digitalWrite(LED2, HIGH);
     delay(150);
digitalWrite(LED5, HIGH); 
digitalWrite(LED2, LOW);
  delay(150);
   digitalWrite(LED7, HIGH); 
   digitalWrite(LED5, LOW); 
  delay(150);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH); 
 delay(150);
digitalWrite(LED6, LOW); 
 digitalWrite(LED3, HIGH); 
      delay(1000);
  digitalWrite(LED7, LOW); 
 digitalWrite(LED6, HIGH);
  digitalWrite(LED3, LOW);   
 delay(250);
digitalWrite(LED6, HIGH); 
 digitalWrite(LED7, HIGH); 
  delay(250);
   digitalWrite(LED5, HIGH); 
 digitalWrite(LED4, HIGH); 
 delay(150);
digitalWrite(LED4, HIGH); 
 digitalWrite(LED3, HIGH); 
   delay(250);
digitalWrite(LED4, LOW); 
 digitalWrite(LED3, LOW);
digitalWrite(LED5, LOW); 
 digitalWrite(LED6, LOW);
 digitalWrite(LED7, LOW); 
 digitalWrite(LED2, LOW);
  delay(450);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
    delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH); 
  delay(50);
 digitalWrite(LED2, LOW); 
    delay(50);
 digitalWrite(LED2, HIGH);
   delay(50);
   digitalWrite(LED2, LOW);
   delay(500);
  }
 
  if (val == 5) { 
delay(500);
    digitalWrite(LED2,HIGH );
    delay(200);
    digitalWrite(LED6,HIGH );
    digitalWrite(LED2,LOW );
    delay(200);
digitalWrite(LED4,HIGH );
digitalWrite(LED6, LOW);
    delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED4,LOW );
    delay(200);
    digitalWrite(LED3,HIGH );
    digitalWrite(LED7,LOW );
    delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
    digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW ); 
 delay(200);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED3,LOW);
 delay(200);
    digitalWrite(LED2,HIGH );
    digitalWrite(LED5,LOW );
        delay(200);
    digitalWrite(LED6,HIGH );
    digitalWrite(LED2,LOW );
   delay(200);
    digitalWrite(LED3,HIGH );
    digitalWrite(LED6,LOW );
    delay(200);
digitalWrite(LED4,HIGH );
digitalWrite(LED6, LOW);
    delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED4,LOW );
    delay(200);
    digitalWrite(LED3,HIGH );
    digitalWrite(LED7,LOW );
  delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
    digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
 delay(200);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED3,LOW );
 delay(200);
    digitalWrite(LED2,HIGH );
    digitalWrite(LED5,LOW );
     delay(200);
    digitalWrite(LED6,HIGH );
    digitalWrite(LED2,LOW );
  delay(200);
    digitalWrite(LED2,HIGH );
    delay(200);
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,LOW );
      digitalWrite(LED6,LOW );
    delay(200);
digitalWrite(LED4,HIGH );
digitalWrite(LED6, LOW);
    delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED4,LOW );
    delay(200);
    digitalWrite(LED3,HIGH );
    digitalWrite(LED7,LOW );
    delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
    digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW ); 
 delay(200);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED3,LOW);
 delay(200);
    digitalWrite(LED2,HIGH );
    digitalWrite(LED5,LOW );
        delay(200);
    digitalWrite(LED6,HIGH );
    digitalWrite(LED2,LOW );
   delay(200);
    digitalWrite(LED3,HIGH );
    digitalWrite(LED6,LOW );
    delay(200);
digitalWrite(LED4,HIGH );
digitalWrite(LED6, LOW);
    delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED4,LOW );
    delay(200);
    digitalWrite(LED3,HIGH );
    digitalWrite(LED7,LOW );
  delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
    digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
  delay(200);
    digitalWrite(LED7,HIGH);
    digitalWrite(LED6,HIGH);
 delay(200);
      digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW );
  delay(200);
      digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
    delay(200);
    digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
  delay(800);
    digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
 delay(1000);
      digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(900);
     digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
 delay(900);
        digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(900);
     digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
 delay(900);
        digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(500);
     digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
            delay(400);
        digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
            delay(200);
    digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,LOW);
    delay(200);
    digitalWrite(LED7,HIGH);
    digitalWrite(LED6,HIGH); 
    digitalWrite(LED4,HIGH ); 
    digitalWrite(LED2,HIGH );
    delay(500);
      digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW); 
    digitalWrite(LED4,LOW ); 
    digitalWrite(LED2,LOW );
    digitalWrite(LED5,HIGH );
    digitalWrite(LED3,HIGH );
  delay(200);
   digitalWrite(LED7,HIGH);
    digitalWrite(LED6,HIGH); 
    digitalWrite(LED5,LOW);
    digitalWrite(LED3,LOW );
  delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW); 
    digitalWrite(LED5,HIGH);
    digitalWrite(LED3,HIGH);
delay(500);
   digitalWrite(LED7,HIGH);
    digitalWrite(LED6,HIGH); 
    digitalWrite(LED5,LOW);
    digitalWrite(LED3,LOW);
  delay(1100);    
     digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW); 
    digitalWrite(LED5,HIGH);
    digitalWrite(LED3,HIGH);
  delay(300);
     digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW); 
    digitalWrite(LED5,HIGH);
    digitalWrite(LED3,LOW);
  digitalWrite(LED2,HIGH);
  delay(500);
       digitalWrite(LED7,HIGH);
    digitalWrite(LED5,LOW);
  digitalWrite(LED2,LOW);
  delay(1000);
   digitalWrite(LED6,HIGH);
 delay(300);
   digitalWrite(LED5,HIGH);
   delay(500);
   digitalWrite(LED4,HIGH);
  delay(1100);
   digitalWrite(LED6,LOW);
 delay(300);
   digitalWrite(LED5,LOW);
   delay(500);
   digitalWrite(LED4,LOW);
   delay(1100);
   digitalWrite(LED7,LOW);
 delay(300);
   digitalWrite(LED6,HIGH);
   delay(500);
   digitalWrite(LED2,HIGH);
  delay(1000);
  digitalWrite(LED3,HIGH);
 digitalWrite(LED4,HIGH);
 delay(300);
   digitalWrite(LED6,LOW);
    digitalWrite(LED5,HIGH);
   delay(500);
   digitalWrite(LED7,HIGH);
  delay(1100);
    
    digitalWrite(LED3,LOW);
 digitalWrite(LED4,LOW);
 delay(300);
   digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW);
   delay(500);
   digitalWrite(LED7,LOW);
    digitalWrite(LED2,LOW);
  delay(1000);
      digitalWrite(LED2,HIGH);
 digitalWrite(LED7,HIGH);
 delay(300);
   digitalWrite(LED6,HIGH);
    digitalWrite(LED3,HIGH);
   delay(500);
   digitalWrite(LED4,HIGH);
    digitalWrite(LED5,HIGH);
  delay(1000);
   digitalWrite(LED2,LOW);
 digitalWrite(LED7,LOW);
 delay(300);
   digitalWrite(LED6,LOW);
    digitalWrite(LED3,LOW);
   delay(500);
   digitalWrite(LED4,LOW);
    digitalWrite(LED5,LOW);
  delay(1000);
  digitalWrite(LED2,HIGH);
 delay(300);
   digitalWrite(LED2,LOW);
   delay(500);
   digitalWrite(LED2,HIGH);
delay(1000);
   digitalWrite(LED3,HIGH);
 digitalWrite(LED4,HIGH);
 delay(300);
   digitalWrite(LED5,LOW);
   digitalWrite(LED6,HIGH);
   delay(500);
   digitalWrite(LED7,HIGH);
  delay(1000);
   digitalWrite(LED3,LOW);
 digitalWrite(LED4,LOW);
 delay(300);
   digitalWrite(LED6,LOW);
   delay(500);
   digitalWrite(LED7,LOW);
  delay(1100);
   digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH);
 delay(300);
   digitalWrite(LED7,HIGH);
   delay(500);
   digitalWrite(LED4,HIGH);
    digitalWrite(LED2,LOW);
  delay(1000);
    digitalWrite(LED2,HIGH);
 delay(300);
   digitalWrite(LED2,LOW);
   delay(500);
   digitalWrite(LED2,HIGH);
delay(1000);
     digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
    delay(500);
      digitalWrite(LED7,HIGH);
    delay(100);
    digitalWrite(LED7,LOW);
    delay(100);
    digitalWrite(LED7,HIGH);
    delay(100);
    digitalWrite(LED7,LOW);
    delay(100);
    digitalWrite(LED7,HIGH);
          digitalWrite(LED6,HIGH);
    delay(100);
    digitalWrite(LED6,LOW);
    delay(100);
    digitalWrite(LED6,HIGH);
    delay(100);
    digitalWrite(LED6,LOW);
    delay(100);
    digitalWrite(LED6,HIGH);
         digitalWrite(LED5,HIGH);
    delay(100);
    digitalWrite(LED5,LOW);
    delay(100);
    digitalWrite(LED5,HIGH);
    delay(100);
    digitalWrite(LED5,LOW);
    delay(100);
    digitalWrite(LED5,HIGH);
      digitalWrite(LED4,HIGH);
    delay(100);
    digitalWrite(LED4,LOW);
    delay(100);
    digitalWrite(LED4,HIGH);
    delay(100);
    digitalWrite(LED4,LOW);
    delay(100);
    digitalWrite(LED4,HIGH); 
        digitalWrite(LED3,HIGH);
    delay(100);
    digitalWrite(LED3,LOW);
    delay(100);
    digitalWrite(LED3,HIGH);
    delay(100);
    digitalWrite(LED3,LOW);
    delay(100);
    digitalWrite(LED3,HIGH);
          digitalWrite(LED2,HIGH);
    delay(100);
    digitalWrite(LED2,LOW);
    delay(100);
    digitalWrite(LED2,HIGH);
    delay(100);
    digitalWrite(LED2,LOW);
    delay(100);
    digitalWrite(LED2,HIGH);
  delay(500);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
        delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(300);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(300);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(300);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(300);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(300);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
         delay(200);     
         digitalWrite(LED7,HIGH );
    digitalWrite(LED6,HIGH);
    digitalWrite(LED5,HIGH );
    digitalWrite(LED4,HIGH );
    digitalWrite(LED3,HIGH );
    digitalWrite(LED2,HIGH );
    delay(200);
   digitalWrite(LED7,LOW);
    digitalWrite(LED6,LOW);
    digitalWrite(LED5,LOW );
    digitalWrite(LED4,LOW );
    digitalWrite(LED3,LOW );
    digitalWrite(LED2,LOW );
  
  
  
  }
  


  
  
}
